// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtI3JDSRHxh-lvQBfz5lyaNwt7Ft44azY',
    appId: '1:411878537183:web:625b8abb048c1f24d2366a',
    messagingSenderId: '411878537183',
    projectId: 'peso-mendez',
    authDomain: 'peso-mendez.firebaseapp.com',
    storageBucket: 'peso-mendez.firebasestorage.app',
    measurementId: 'G-B3JWTG6LVC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwPUeEdyao74gboFqoLDOV5bYDlf8W7qk',
    appId: '1:411878537183:android:76f3cec956a419dbd2366a',
    messagingSenderId: '411878537183',
    projectId: 'peso-mendez',
    storageBucket: 'peso-mendez.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsZblJTCgWN1zR4rZUE9-2HfKaATMgnwA',
    appId: '1:411878537183:ios:c33f35e5c0d856bcd2366a',
    messagingSenderId: '411878537183',
    projectId: 'peso-mendez',
    storageBucket: 'peso-mendez.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsZblJTCgWN1zR4rZUE9-2HfKaATMgnwA',
    appId: '1:411878537183:ios:c33f35e5c0d856bcd2366a',
    messagingSenderId: '411878537183',
    projectId: 'peso-mendez',
    storageBucket: 'peso-mendez.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtI3JDSRHxh-lvQBfz5lyaNwt7Ft44azY',
    appId: '1:411878537183:web:b55d097ce69bbb20d2366a',
    messagingSenderId: '411878537183',
    projectId: 'peso-mendez',
    authDomain: 'peso-mendez.firebaseapp.com',
    storageBucket: 'peso-mendez.firebasestorage.app',
    measurementId: 'G-4KQG11TZHS',
  );
}
